### ISSUE TITLE
Onboarding layout isn't mobile friendly

### ISSUE THREAD

**Issue by ktra99** [Mirrorful/mirrorful#101]
<img width="2236" alt="Screenshot 2023-03-05 at 23 50 12" src="https://user-images.githubusercontent.com/82717216/222990428-37aa8dba-3da4-4e6e-994a-b2d3dca7445d.png">

**Comment by ktra99** [comment]
I would like to help work on this issue 🙂

**Comment by alexdanilowicz** [comment]
Hi @ktra99!  My gut reaction is because Mirrorful is an NPM package, it is extremely unlikely for someone to be using it on mobile. Howeve,  I agree it should be responsive, especially as right now it is not responsive on small laptop screens. Responsive for small laptop screens is more important than mobile.

If you do this issue, please use Charka UI responsive object syntax styles. https://chakra-ui.com/docs/styled-system/responsive-styles#the-object-syntax

You are welcome to work on this, but with the above all in my mind, I cannot promise you we will merge it in if it ends up being a lot of code and difficult to maintain due to the fact that mobile is simply not a frequent use case.
