### ISSUE TITLE
Shadow sliders and shadow color picker won't update when modifying input value

### ISSUE THREAD

**Issue by joelcmk** [Mirrorful/mirrorful#257]
When the user updates the variant value input, it should update the color picker/siders as well. Here is a loom of the issue. 

https://www.loom.com/share/3682b89eefa24a4faa59cc73cbf7a17e

**Comment by ktra99** [comment]
The problem is that the preview box relies on the input from `codeResult` which gets its input from `hOffset, vOffset, blur, spread, color`

The input bar itself triggers an onChange event directly to the variant state which is used to **save** the result not project the values directly to the preview box. -

```
onChange={(e) =>
  setVariant({ ...variant, name: e.target.value })
}
```

I would happy to work further on this issue
