### ISSUE TITLE
Feature request: Implement a more fluent color picking experience

### ISSUE THREAD

**Issue by ktra99** [Mirrorful/mirrorful#261]
Inspiration - https://uicolors.app/create

https://www.loom.com/share/36a89dec15e04e399b45ce362f0a7f15

Love about UI colors
- Able to view variants as I change color
- Able to view contrast table for a11y purposes
- "Edit section" is more extensive e.g. I'm able to change lightness and saturation of the entire variant scheme
- UI colors has two tabs one for testing, one for editing and I'm able to toggle in-between, which allows me to test the colors as I'm selecting.
- Intuitive UI

Don't like about current Mirrorful experience:
- If I want to edit a variant I have to click on the 3 dot icon then I have to press edit and then I can change the color and finally I can save the changes. Resulting in a total of 4 clicks. With UI colors I can edit a variant directly
- Once I save a color, Each variant is treated individually. Meaning I have to edit each variant whereas UI colors allows me to edit any variant of any color very smoothly
- I have no real way of testing out my colors inside the mirrorful editor. Currently what I tend to do is switch between the editor and my own application to visualize. Having a premade component template like UI colors inside the editor would help a lot in that retrospect.

<img width="2239" alt="Screenshot 2023-03-31 at 22 42 23" src="https://user-images.githubusercontent.com/82717216/229225707-0daf8c7e-e4a5-4d20-b926-24d6bad7a79c.png">

<img width="2239" alt="Screenshot 2023-03-31 at 22 42 34" src="https://user-images.githubusercontent.com/82717216/229225737-3ff897a0-e703-4224-b60e-9255b6706a16.png">

**Comment by alexdanilowicz** [comment]
@ktra99 thanks for opening! Could you share exactly what you _don't_ like about Mirrorful today? And what you would like in the future? (What do you LOVE about uicolors?) Some bullet points would be super helpful

------

Love about UI colors
- ....

Don't like about current Mirrorful experience:
-....

**Comment by alexdanilowicz** [comment]
Thanks @ktra99 !

I'll also add that I closed https://github.com/Mirrorful/mirrorful/issues/225 and instead decided all color picker improvements should just be discussed here.

**Comment by joelcmk** [comment]
About issue #225, I came across this [library](http://casesandberg.github.io/react-color/) it is kind of the same as the [one we use now](https://colorpickerexamples.hellopangea.dev/?path=/story/examples-basic--basic). But as far as I can tell it is more responsive (it may need some extra testing though). Other options could be: 

1. [HTML native color picker](https://developer.mozilla.org/en-US/docs/web/html/element/input/color): The only issue that I see with this, is that it won't let you change the opacity but it can be fixed by adding an extra slider. 
2. [React colorful](https://omgovich.github.io/react-colorful/): This is a simpler color picker but I think that it has all of the options that we need.

**Comment by alexdanilowicz** [comment]
I think I like React colorful the best, we need to move off of our existing one for sure. Thanks for outlining Joel.
