### ISSUE TITLE
Truncate length of the displayed variant name on the fontsizes page and shadows page

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#271]
<img width="584" alt="Screen Shot 2023-03-31 at 1 01 11 PM" src="https://user-images.githubusercontent.com/29822597/229218507-8a742d13-de12-4ca8-881b-c7ebec358e9c.png">
<img width="872" alt="Screen Shot 2023-03-31 at 1 02 15 PM" src="https://user-images.githubusercontent.com/29822597/229218686-684883db-98cb-4995-84a1-941feb59a669.png">

We should truncate and add ellipses. For example:
<img width="132" alt="Screen Shot 2023-03-31 at 1 03 02 PM" src="https://user-images.githubusercontent.com/29822597/229218809-45b6fdda-b90f-4b8b-badc-e757ea09d5a0.png">

**Comment by rCirelli** [comment]
Hey @alexdanilowicz , I took the liberty to try and implement the expected behavior:

![image](https://user-images.githubusercontent.com/22369220/229231257-fb75eab0-9654-47eb-958a-7a16bee41bbb.png)


![image](https://user-images.githubusercontent.com/22369220/229231347-6f3eb91c-1d47-4c27-bb25-6e6130140ca6.png)


[PR](https://github.com/Mirrorful/mirrorful/pull/272)

**Comment by alexdanilowicz** [comment]
Ah thanks @rCirelli ! Looks like @danielrees8743 also made a PR and that was merged in slightly before (but around the same time as yours) thank you so much! There are still other issues if you're interested.
