### ISSUE TITLE
Clean up tailwind export

### ISSUE THREAD

**Issue by sugamadhiakri** [Mirrorful/mirrorful#284]
Context: 

![image](https://user-images.githubusercontent.com/27858990/230065468-4b2f98aa-bf29-43b0-bab4-167ccd5fba7e.png)

**Comment by sugamadhiakri** [comment]
The idea is: users can generate tailwindcss theme automatically from the web app without having to install the package.

**Comment by alexdanilowicz** [comment]
@Teddarific I think we should change the `CJS` to say `Tailwind` and just give an example of the tailwind config file. 

Thanks for opening this @sugamadhiakri.

**Comment by alexdanilowicz** [comment]
@sugamadhiakri go for it! just assigned you

**Comment by alexdanilowicz** [comment]
Love it when someone opens an issue and then they fix it themselves! incredible!

**Comment by Teddarific** [comment]
Yep, like the idea of just converting `CJS` to `Tailwind`. 

One gotcha here is that we need to rename base to `DEFAULT` for Tailwind, that's a huge annoyance right now for Tailwind users.

So for this task, 

- [ ] Convert CJS -> Tailwind in both the web editor + local package file type. Let's rename the `theme.cjs` file to like `tailwind.cjs` or something, and `cjs` -> `Tailwind` in the web editor
- [ ] For this new Tailwind type, translate the base color to map to `DEFAULT:` instead of `base:` in the `theme.cjs`

**Comment by alexdanilowicz** [comment]
@sugamadhiakri FYI on the above^^^^

Also I think we should keep the theme.cjs export BUT also include a tailwind.cjs file. That way no breaking changes.

**Comment by sugamadhiakri** [comment]
@alexdanilowicz 

Thank you for the clarification.
