### ISSUE TITLE
UI Suggestion - Color Palette Page

### ISSUE THREAD

**Issue by gurvirboparai** [Mirrorful/mirrorful#314]
Hi, I have recently saw Mirrorful on YouTube and thought this would be great in my endeavors of UX/UI Design for my own projects. After reading on slack I saw someone suggest the UI on the color palette be changed. Here is my suggestion:

![mirroful-wireframe](https://user-images.githubusercontent.com/87482672/231548078-8e53a9c9-d8aa-4ec9-b57f-a55c7bca3a2c.png)

**Comment by alexdanilowicz** [comment]
From @Teddarific: Thanks for taking a crack at this!! Let me think on this some more — I have some ideas of my own, I know @karanvirsb has some ideas, and looks like you have some awesome ideas!
What might be fun is for us to start a collaborative CodePen or Figma or something that we can all hack and iterate on.
I'd like to spend some more time with this redesign, since we've been through a few iterations already haha

Slack convo: https://mirrorful.slack.com/archives/C04QKTVD8FP/p1681325124019689?thread_ts=1681324021.805129&cid=C04QKTVD8FP

**Comment by alexdanilowicz** [comment]
I'm going to close this for now and leave the discussion in Slack until we decide on a design.
