### ISSUE TITLE
Sidebar items are not hyperlinks

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#334]
While this does not block me from using the app, I'm also not able to use the `Open in a new tab` function

![image](https://user-images.githubusercontent.com/20909078/232959378-b87dfe7c-62f8-4838-878f-dfeb3b87e48c.png)

**Comment by Pranav2612000** [comment]
Actually I was planning to work on it, but you can pick it up. Let me know if you need any help.

**Comment by alexdanilowicz** [comment]
@Pranav2612000 because you made the issue, do you want to work on it? I'll assign to you for now.

Looks like the fix would be to use a Link component instead of a Box. Something like that. Please ensure that the styling we use today persists.

https://github.com/Mirrorful/mirrorful/blob/main/packages/core/src/components/Sidebar/Sidebar.tsx#L61

Good find. I'm all for the accessibility.

**Comment by alexdanilowicz** [comment]
Actually @Pranav2612000, see you're working on the Typography custom input feature, so I think as you work on that, let's have @Bismay5467 work on this, and once you finish that, if this is still done you can do it.

@Bismay5467 — this issue is assigned to you!

**Comment by Pranav2612000** [comment]
There are other ways we can ensure that the 2 windows communicate, but I
don't think we need it to be realtime. It's fine if the user sees older
data, as long as the latest data is fetched on page refresh or on
navigating to a new tab.
